language: node_js
node_js:
  - "9"
before_script:
  - npm install
script: npm run build
   - cp dist/GDM-front/index.html dist/GDM-front/404.html
deploy:
  local-dir: dist/top-collegues-front
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch:
      - master
      - dev
notifications:
    email:
    recipients:
      - youcef.handoura@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
